### ISSUE TITLE
Do you think that maybe Apple has already secretly developed bootcamp for M1 Macs but haven't released nor announced due to lack of licensing for Windows on ARM? 

### ISSUE THREAD

**Issue by YousufSSyed** [amarioguy/NTASPProjectSiteDeprecated#1]
[Federighi says Windows on ‌M1‌ Macs is "up to Microsoft."](https://www.macrumors.com/2020/11/20/craig-federighi-on-windows-for-m1-macs/)

> As for Windows running natively on the machine, "that's really up to Microsoft," he said. "We have the core technologies for them to do that, to run their ARM version of Windows, which in turn of course supports x86 user mode applications. But that's a decision Microsoft has to make, to bring to license that technology for users to run on these Macs. But the Macs are certainly very capable of it."

It's also worth noting that [rEFIt](https://en.wikipedia.org/wiki/REFIt) was a boot menu made for booting multiple operating systems on Intel Macs and first released on March 2nd 2006. Only a month later on April 5th 2006 Apple released [Bootcamp](https://en.wikipedia.org/wiki/Boot_Camp_(software)) for Intel Macs.

**Comment by amarioguy** [comment]
While on one hand I can see where the argument comes from - there's just been no evidence of Microsoft ever planning or considering Windows support for Apple silicon platforms, no evidence internally in the Windows kernel of anything critical changing or any word about it. (though I could be wrong on this)

While it's likely been considered, the value proposition at the time is just not there. Also the rEFIt example is a bad one because rEFIt did still see much more use even post-Bootcamp because Apple's EFI implementation at the time was too restrictive.

Furthermore Microsoft to my knowledge builds Windows around standard hw platforms and with very very rare exceptions, would prefer OEMs to do the same, and Apple hardware requires more than just a few tiny changes to Windows. It would also require them to have HW documentation from the corp and all.

My stance is this - if Microsoft ever came out to announce official support, I'll work from there. Until then, I have to assume it's not in the immediate future.

**Comment by YousufSSyed** [comment]
@amarioguy Good answer, but it doesn't answer my question of what you about if _apple_ is thinking of or already did so behind closed doors.

**Comment by amarioguy** [comment]
You yourself said that Apple deferred the question to Microsoft, Apple making any sort of "Bootcamp 2" isn't happening without Microsoft's cooperation in making windows work. 

Furthermore, due to how the boot model works, you need to be physically present in the recovery environment for this sort of thing to even be possible.

To directly answer the question: I don't know if Apple is thinking about possibly working with MS to make this happen. If they are and something comes out, cool, that's okay with me. This is about running Windows unofficially
