### ISSUE TITLE
Work

### ISSUE THREAD

**Issue by Potatococ** [amarioguy/NTASPProjectSiteDeprecated#2]
Are you still working on this?

**Comment by amarioguy** [comment]
Hello!

Yes, I’m still working on this, the past month’s just been really busy and all but I’m still working on this (you can always check the EFI and m1n1_windows repos to gauge where I’m at but the short of it is I’m now refactoring my EFI codebase to make it more adaptable to multiple machines (since it was previously designed with only the machines I had on hand in the past) and working on the ACPI tables needed to boot Windows

**Comment by Potatococ** [comment]
Nice

**Comment by DownBeatGnu7882** [comment]
Thank you for the hard work!
